first_asio: first_asio_server first_asio.cpp
	g++ first_asio.cpp -o first_asio -lpthread -lboost_system
first_asio_server: first_asio_server.cpp
	g++ first_asio_server.cpp -o first_asio_server -lpthread -lboost_system
