first_asio: first_asio_server first_asio.cpp
	g++ first_asio.cpp -o client -lpthread -lboost_system -std=c++11
first_asio_server: first_asio_server.cpp
	g++ first_asio_server.cpp -o server -lpthread -lboost_system -std=c++11
